In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.metrics import mean_squared_error

In [2]:
y_pred=tf.constant([1.1,20.2,230.3,120.4,500.2,6.3])
y_true=tf.add(y_pred,tf.ones_like(y_pred))

In [3]:
print(y_pred)
print(y_true)

tf.Tensor([  1.1  20.2 230.3 120.4 500.2   6.3], shape=(6,), dtype=float32)
tf.Tensor([  2.1  21.2 231.3 121.4 501.2   7.3], shape=(6,), dtype=float32)


In [6]:
tf.math.reduce_variance(y_true)

<tf.Tensor: shape=(), dtype=float32, numpy=31592.697>

In [ ]:
y_true_next = y_true[1:]
y_pred_next = y_pred[1:]
#extract the "today's price" of tensor
y_true_tdy = y_true[:-1]
y_pred_tdy = y_pred[:-1]

In [ ]:
y_true_tdy

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([2.1, 3.2, 4.3, 5.4, 6.2], dtype=float32)>

In [ ]:
#substract to get up/down movement of the two tensors
y_true_diff = tf.subtract(y_true_next, y_true_tdy)
y_pred_diff = tf.subtract(y_pred_next, y_pred_tdy)
#create a standard tensor with zero value for comparison
standard = tf.zeros_like(y_pred_diff)
#compare with the standard; if true, UP; else DOWN
y_true_move = tf.greater_equal(y_true_diff, standard)
y_pred_move = tf.greater_equal(y_pred_diff, standard)

In [ ]:
y_true_move

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([ True,  True,  True,  True,  True])>

In [ ]:
condition = tf.equal(y_true_move, y_pred_move)
indices = tf.where(condition)
ones = tf.ones_like(indices)
# indices = tf.add(indices, ones)

In [ ]:
indices
# ones


<tf.Tensor: shape=(5, 1), dtype=int64, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5]])>

In [ ]:
direction_loss = tf.Variable(tf.ones_like(y_pred), dtype='float32')
updates = tf.cast(tf.ones((5,)), dtype='float32')
alpha = 1000

In [ ]:
print(direction_loss)
print(alpha*updates)
print(indices)

<tf.Variable 'Variable:0' shape=(6,) dtype=float32, numpy=array([1., 1., 1., 1., 1., 1.], dtype=float32)>
tf.Tensor([1000. 1000. 1000. 1000. 1000.], shape=(5,), dtype=float32)
tf.Tensor(
[[0]
 [1]
 [2]
 [3]
 [4]], shape=(5, 1), dtype=int64)


In [ ]:
direction_loss = tf.tensor_scatter_nd_update(direction_loss, indices, alpha*updates)

In [ ]:
direction_loss

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1000., 1000., 1000., 1000., 1000.,    1.], dtype=float32)>

In [ ]:
loss = tf.Variable(tf.zeros_like(y_pred), dtype='float32')

In [ ]:
se=tf.sqrt(tf.subtract(y_true,y_pred))

In [ ]:
se

<tf.Tensor: shape=(6,), dtype=float32, numpy=
array([0.99999994, 1.        , 1.0000001 , 1.        , 1.        ,
       1.        ], dtype=float32)>

In [ ]:
classes_factor=[-np.inf,70.1,100.1,200.1,np.inf]
tf.constant(classes_factor[0])

<tf.Tensor: shape=(), dtype=float32, numpy=-inf>

In [ ]:
update=tf.ones_like(index,dtype='float32')

In [ ]:
for i in range(1, len(classes_factor)):
            index1 = tf.where(tf.logical_and(tf.less_equal(tf.constant(classes_factor[i - 1]), y_true)
                               , tf.greater(tf.constant(classes_factor[i]),y_true)))
            index2 = tf.logical_and(tf.less_equal(tf.constant(classes_factor[i - 1]), y_true)
                               , tf.greater(tf.constant(classes_factor[i]),y_true))
            print(index)
            update=se[index2]*i
            print(update)
            loss=tf.tensor_scatter_nd_update(loss, index1, update)

tf.Tensor(
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]], shape=(6, 1), dtype=int64)
tf.Tensor([0.99999994 1.         1.        ], shape=(3,), dtype=float32)
tf.Tensor(
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]], shape=(6, 1), dtype=int64)
tf.Tensor([], shape=(0,), dtype=float32)
tf.Tensor(
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]], shape=(6, 1), dtype=int64)
tf.Tensor([3.], shape=(1,), dtype=float32)
tf.Tensor(
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]], shape=(6, 1), dtype=int64)
tf.Tensor([4.0000005 4.       ], shape=(2,), dtype=float32)


In [ ]:
y_true

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([2.1, 3.2, 4.3, 5.4, 6.2, 7.3], dtype=float32)>

In [ ]:
loss

<tf.Tensor: shape=(6,), dtype=float32, numpy=
array([0.99999994, 1.        , 4.0000005 , 3.        , 4.        ,
       1.        ], dtype=float32)>